Maps и Sets
eugene2806/JavaScript-ADVANCED pull request #1
Opened 2023-10-03 09:41 UTC by eugene2806

2023-10-04 17:09 UTC, Levitinn requested changes

2023-10-04 17:09 UTC, Levitinn commented on 1-map/app.js
> +let Array1 = [
имена переменным нужно задавать с маленькой буквы

2023-10-04 17:09 UTC, Levitinn commented on 1-map/app.js
> +console.log(Array1)
решение работает, но довольно тяжело воспринимать.
давай попробуем избавиться от forEach и использовать только map и find

2023-10-05 17:02 UTC, eugene2806 commented on 1-map/app.js
> +let Array1 = [
Как я это проморгал непонятно)

2023-10-05 17:03 UTC, eugene2806 commented on 1-map/app.js
> +console.log(Array1)
Переделал

2023-10-06 15:43 UTC, Levitinn approved these changes
хорошо)

2023-10-06 15:43 UTC, Levitinn commented on 1-map/app.js
> +});
<img width="316" alt="image" src="https://github.com/eugene2806/JavaScript-ADVANCED/assets/44999446/d9b6b662-e5da-43b8-991c-4e50212410d2">

2023-10-06 15:51 UTC, eugene2806 commented on 1-map/app.js
> +});
Точно. Спасибо. А мне самому Merge веток делать?

2023-10-06 15:59 UTC, Levitinn commented on 1-map/app.js
> +});
да, если я апрувлю, ты можешь делать мердж

2023-10-06 16:00 UTC, eugene2806 commented on 1-map/app.js
> +});
Понял

2023-10-06 16:01 UTC, merged