SOLID
eugene2806/JavaScript-ADVANCED pull request #8
Opened 2023-10-30 09:55 UTC by eugene2806

2023-10-30 15:03 UTC, Levitinn requested changes

2023-10-30 15:03 UTC, Levitinn commented on 8-solid/app.js
> +bil.fixBilling();
ты можешь вызывать  этот метод внутри конструктора FixBilling, тогда не придется вызывать этот метод для каждого нового инстанса ( если такие будут), и тогда, у FixBilling сразу после инициализации будет свойство рассчитанное свойство amont ( а у тебя оно undefined до тех пор, пока не вызовешь этот метод.
подобная ситуация у тебя на 44 и 46 строке с методами hourBilling, itemBilling

2023-10-31 06:13 UTC, eugene2806 commented on 8-solid/app.js
> +bil.fixBilling();
Исправил, если правильно понял)

2023-10-31 08:17 UTC, Levitinn commented on 8-solid/app.js
> +bil.fixBilling();
не правильно. ты можешь вызвать метод fixBilling внутри конструктора класса fixBilling, на этапе его инициализации. тогда создавая new FixBilling(...args), тебе не нужно будет после этого вызывать его метод, для расчета свойств.
`class FixBilling extends Billing {
    constructor(array) {
        super(array)
        this.fixBilling()
    }
     fixBilling() {
        this.amount = this.calculateTotal();
        return this.amount;
     }

}`

2023-11-02 10:39 UTC, eugene2806 commented on 8-solid/app.js
> +bil.fixBilling();
Теперь дошло

2023-11-02 19:32 UTC, Levitinn approved these changes
молодец)

2023-11-07 04:28 UTC, merged